### ISSUE TITLE
[Bug]: Segments tool is broken with manhattan router

### ISSUE THREAD

**Issue by alexandernst** [clientIO/joint#2300] opened 2023-08-15 11:03 UTC
### What happened?

Segment tool seems to be broken when used with manhattan (and other?) routers.

Demo: https://codesandbox.io/s/joint-link-manhattan-bug-n3v4z4

Instructions: Just hover the link with the cursor, then click on the segment and try to drag it.

### Version

3.7.5

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What operating system are you seeing the problem on?

Mac

**Comment by kumilingus** [comment] 2023-08-15 11:20
Duplicate of https://github.com/clientIO/joint/issues/2044.

**Closed by kumilingus** 2023-08-15 11:20 UTC
Labels: bug

**Comment by alexandernst** [comment] 2023-08-15 11:24
Ooh, I see 🤔. Indeed using segments with a manhattan router is a little bit weird. 🙏
