### ISSUE TITLE
Magnet not found with `findBySelector`

### ISSUE THREAD

**Issue by BoykoAlex** [clientIO/joint#898] opened 2018-06-12 14:10 UTC
https://plnkr.co/edit/LX4Y8YI4ijhQYwqOhwH9?p=preview

From the plunker above you'd see START and END nodes. Start has output port, End has input port. Try connecting Start to End. Note that connection at END node anchoring at the shape border rather than the port. This is simply because it cannot find the magnet from the selector JointJS created.

Note that if I change markup of the end node slightly like this:
```
    '<g class="composed-task">' +
    '<circle class="input-port"/>' +
    '<g class="shape">' +
    '<circle class="inner"/>' +
    '<circle class="outer"/>' +
    '<text class="label"/>' +
    '</g>' +
    '</g>',
```

**Comment by kumilingus** [comment] 2018-06-13 15:59
Hi Alex,

the problem is that two instead of one magnet are actually found. Meaning the result determined by the selector is ambiguous.

For the selector

```
g:nth-child(1) > circle:nth-child(2)
```
 and the following structure
```
    '<g class="composed-task">' +
    '<g class="shape">' +
    '<circle class="inner"/>' +
    '<circle class="outer"/>' +
    '<text class="label"/>' +
    '</g>' +
    '<circle class="input-port"/>' +
    '</g>',
```

both `.outer` and `.input-port` circles are found.

The solution would be to change the selector to this.
```
> g:nth-child(1) > circle:nth-child(2)
```

Fix (I'll create a PR soon)
```javascript
joint.dia.Cell.prototype.getSelector = function(el, prevSelector) {

        var selector;

        if (el === this.el) {
            if (typeof prevSelector === 'string') selector = '> ' + prevSelector;
            return selector;
        }

        if (el) {

            var nthChild = V(el).index() + 1;
            selector = el.tagName + ':nth-child(' + nthChild + ')';

            if (prevSelector) {
                selector += ' > ' + prevSelector;
            }

            selector = this.getSelector(el.parentNode, selector);
        }

        return selector;
}
```

---

I suggest using JSON markup (https://resources.jointjs.com/docs/jointjs/v2.1/joint.html#dia.Cell.markup) instead of serialized XML.
If you define the `selector` property (a unique string) in the JSON Markup for a particular magnet, this will be used later for finding this magnet. This is faster, it allows you to target subelements of a port and does not pollute the link's model with ugly CSS `g:nth-child(1) > circle:nth-child(2)` selector.

**Comment by kumilingus** [comment] 2018-06-15 18:14
Fixed with https://github.com/clientIO/joint/commit/bfd2024f69e13979cc3010d4d9fc43a5348b29aa.

**Closed by kumilingus** 2018-06-15 18:14 UTC
