### ISSUE TITLE
[Bug]: Can't import the named export 'V' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by Hemal-LPT218** [clientIO/joint#2715] opened 2024-07-23 06:16 UTC
### Current versus expected behaviour

After installing the JointJS+ library using file installation, errors occur when running the project after importing the JointJS+ library.
![error after import jointjs](https://github.com/user-attachments/assets/25e03d55-cb3e-437a-ad50-513000cd1735)

### Steps to reproduce

"react": "16.11.0",
"react-dom": "16.11.0",
"react-scripts": "3.1.1",
"@types/node": "13.13.52",
"@types/react": "16.9.11",
"typescript": "4.1.3"

This version was in my project. After installing the JointJS+ library, I created a demo as shown in the React example and ran the project but got an error.

### Version

4

### What browsers are you seeing the problem on?

Firefox

### What operating system are you seeing the problem on?

Linux

**Comment by kumilingus** [comment] 2024-07-23 09:33
Duplicate of https://github.com/clientIO/joint/discussions/2714.

**Closed by kumilingus** 2024-07-23 09:33 UTC
Labels: bug
