### ISSUE TITLE
Dragging multiple selected elements

### ISSUE THREAD

**Issue by Ndmanh123** [clientIO/joint#1670] opened 2022-05-19 02:21 UTC
Hi i'm using JointJS and Rappid 3.5. i'm trying to implement selecting multiple elements in a similar way as in Kitchensink https://resources.jointjs.com/demos/kitchensink
I didn't have any issue with implementing selecting multiple elements but when i drag one of the selected element .Is there some configuration I have to use to make it drag the whole selection ? look like dragging all selected element should be the default behavior ,am i right? can't any one tell me how to make it work

**Comment by kumilingus** [comment] 2022-05-19 08:10
Duplicate of #1669.

**Closed by kumilingus** 2022-05-19 08:10 UTC
