### ISSUE TITLE
[Bug]: textWrap is not calculating properly text size when using custom fonts / size (Bootstrap repro)

### ISSUE THREAD

**Issue by alexandernst** [clientIO/joint#2295] opened 2023-08-11 20:01 UTC
### What happened?

It seems that textWrap isn't working as expected when using css styling. A simple repro: https://codesandbox.io/s/textwrap-bug-76f2md?file=/src/index.js

Note that commenting the bootstrap import fixes the issue.

![image](https://github.com/clientIO/joint/assets/89727/5d4872d0-c46d-4dd6-990e-14028cc0bf3f)

### Version

3.7.5

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What operating system are you seeing the problem on?

Mac

**Comment by kumilingus** [comment] 2023-08-14 10:46
Now you must explicitly set all font-related attributes in the `<text>` element for the `textWrap` function to work correctly. Back then, this decision was made consciously for performance reasons.

Now it is probably a good time to use the `getComputedStyle()` function to retrieve the actual font attributes needed to calculate the text wrap.

**Comment by alexandernst** [comment] 2023-08-28 11:59
@kumilingus is this going to make it in the next patch release (3.7.6?) or will it land in 4.0.0? If the later, is there any workaround that I can apply?

**Comment by kumilingus** [comment] 2023-08-28 15:40
Sorry, haven't made the decision yet.

A workaround is to re-define the `textWrap` attribute. It can be done per element, as shown below.

```js
class MyRect extends joint.dia.Element {

    static attributes = {
        textWrap: {
            qualify: joint.util.isPlainObject,
            set: function(value, refBBox, node, attrs) {
                const computedFontSize = parseFloat(getComputedStyle(node).fontSize);
                const computedAttrs = { ...attrs };
                computedAttrs.fontSize = computedFontSize;
                joint.dia.attributes.textWrap.set.call(this, value, refBBox, node, computedAttrs);
            }
        }
    };
}
```

Here's updated version of your codesandbox:
https://codesandbox.io/s/textwrap-bug-forked-svgjq9?file=/src/index.js

**Comment by alexandernst** [comment] 2023-08-29 23:32
Hi! I was finally able to get to this. I tried it, but it doesn't seem to be working as expected. Resizing the cell makes the text overflow the width.

![image](https://github.com/clientIO/joint/assets/89727/7ad082c9-c3bc-4711-978d-4698ca18f118)

**Comment by kumilingus** [comment] 2023-08-30 17:06
I think that only `text-transform` applies to SVG.

IMHO `text-shadow` does not affect the text. It only adds a shadow next to the text. But it is a matter of interpretation.

Note that there is no `line-height` in SVG. It's a property that we introduced in the `Vectorizer.text()` method.

**Comment by kumilingus** [comment] 2023-09-12 12:34
Fix waits for #2335. For the time being please use the workaround.

It's currently not guaranteed that the `font-size` is already set on the SVGNode (because it is a special attribute - because of `calc()`). i.e. the computed style might return incorrect font size (whatever the font size is before the font-size attribute is set).

**Comment by coyoteecd** [comment] 2023-09-13 10:53
Another workaround that I've used in our project for a similar problem (body style, including font family/size/weight affected the SVG text but did not get taken into account when calculating wrapping) is to set the text attributes explicitly with references to CSS variables. For me this solved the text wrapping without being forced to duplicate values between the CSS file and the TypeScript file containing the shape definition.

E.g.
```
{
  text: {
    fontFamily: 'var(--my-body-font-family)',
    fontWeight: 'var(--my-body-font-weight)',
    fontSize: 'var(--my-body-font-size)',
    textWrap: {
      width: '97%' // padding
    }
  }
}
```

Recent versions of Bootstrap already define CSS vars, so you might be able to use them as-is.

**Comment by alexandernst** [comment] 2024-02-12 09:33
I thought this was going to land in 4.0 since it's a breaking change 🤔
maybe in a future 4.x release?

**Comment by kumilingus** [comment] 2024-02-12 10:43
The necessary breaking change was made and the issue can be fixed with a patch now (`4.0.x`).

**Closed** 2024-02-19 09:24 UTC
Labels: enhancement

**Comment by zbynekstara** [comment] 2024-04-12 15:31
Hi @alexandernst, the fix was released as part of JointJS v4.0.2 (JointJS+ v4.0.1).

**Comment by alexandernst** [comment] 2024-05-07 17:58
Thank you @zbynekstara !!

**Comment by frnora** [comment] 2024-08-21 15:23
After this change: For our custom shapes the `breakText` is called with wrong params  (from `updateViewsAsync` -> `...` -> `updateRelativeAttributes` -> `set`). It is not respecting the properties set in the markup.

```js
export default class CustomElement extends dia.Element {

    preinitialize() {
        super.preinitialize(...arguments);
        // etc.
    }

    // etc.

    defaults() {
        return {
            type: 'xyz',
            size: { width: 200, height 60 },
            attrs: {
                // etc.
                label: {
                    textAnchor: 'start',
                    text: '',
                    textWrap: {
                        width: 160,
                        ellipsis: true,
                        maxLineCount: 3
                    },
                    x: 20,
                    fontSize: 'var(--test-font-size, 14px)',
                    fontFamily: 'var(--test-font-family, sans-serif)',
                    fill: 'var(--test-fill-color, #333)'
                }
            }
        };
    }

   // etc.
}
```
`fontSize`, `fontFamily` from the markup are ignored, I guess they are set later than the view update is executed? That means the `breakText` will try to break a (e.g.) 12px font-sized default, while the `--test-font-size` could be set to e.g. 20px. So it won't break it and the text will overflow the element (body, or whatever).

This was working flawlessly before this change. I will write an override to take those values from the `attrs` as it was before unless you have a better idea. But I am not quite sure whether this is the intended behavior.

Thanks.

**Comment by frnora** [comment] 2024-08-27 11:13
Hi @kumilingus, thank you, that's great to hear! 

Sadly, it's not part of the latest joint+ dist, thus I can't use it. (must rely on that file) I will keep in mind to remove the override once a new version joint+ hits.
