### ISSUE TITLE
util.js:49 Uncaught TypeError: Cannot set property 'rank' of undefined

### ISSUE THREAD

**Issue by mattbigb** [clientIO/joint#481] opened 2016-11-30 05:22 UTC
I've been successfully using the following code to layout the graphs cells. I have some cells contained within another cell with various links between the inner cells. I have now added a port to the containing cell and link inner cells to this. This port link is drawn correctly. However when I use the below layout code, I get an error. 

I tried a few things but cannot get the layout to work without an error.

```
                var nodeGraph = joint.createGraph();    // Copy graph structure
                var cloneMap = graph.cloneCells(graph.getCells());
                nodeGraph.addCells(_.map(cloneMap, function(val) { return val; }));
                joint.layout.DirectedGraph.layout(nodeGraph, {
                    setLinkVertices: false,
                    rankDir: "BT",
                    edgeSep: 20,
                    clusterPadding: { top: padding, left: padding, bottom: 45, right: padding },
                    marginX: 20,
                    marginY: 20
                });
```

Here' s a screenshot showing the graph with the additional link to the containers port.

![screenshot from 2016-12-01 15-00-23-cleaner](https://cloud.githubusercontent.com/assets/24263604/20740509/5f08db36-b70f-11e6-8c8f-4f1d27b951ca.png)

Stacktrace:
[stacktrace.txt](https://github.com/clientIO/joint/files/621020/stacktrace.txt)

jointjs version 0.9.10
dagre version 0.7.4

**Comment by kumilingus** [comment] 2016-11-30 06:59
Duplicate of #455.

**Closed by kumilingus** 2016-11-30 06:59 UTC
