### ISSUE TITLE
Links going haywire when importing fromJSON

### ISSUE THREAD

**Issue by snehal96** [clientIO/joint#1187] opened 2019-09-24 05:40 UTC
Hey, I have been working on jointjs creating graphs. It all works fine till I am not importing my created graph from json.
When, I am making the graph, everything looks fine, works fine but when I export the graph and import it back the link source and target are changed to the cell instead of the port to which it initially assigned.

I have tried a lot but have hit a bottleneck and do not know what to do.
Using jointjs v3.0.2
 
the actual graph
![j1](https://user-images.githubusercontent.com/26721118/65484002-b9dc8b80-debb-11e9-84aa-f602bd54da2d.png)

the graph generated from json
![j2](https://user-images.githubusercontent.com/26721118/65484026-d082e280-debb-11e9-8dab-6cf3964e10c3.png)

**Comment by snehal96** [comment] 2019-09-24 14:45
I tried with that, but in that when trying to add port through a json
object it gives me a domexception: invalidcharacterexception, 0 is not a
valid string literal, somehing like that. So, I switched back to 3.0.2

**Comment by kumilingus** [comment] 2019-09-24 16:39
I believe this has been fixed in `v3.0.3` (by this PR https://github.com/clientIO/joint/pull/1146/files). You might need to focus on the other error (domexception) you were experiencing after the upgrade. Do you know how to reproduce that?

**Comment by snehal96** [comment] 2019-09-24 16:59
Well, I don't exactly know how to reproduce the error but whenever I tried
to insert ports dynamically as a json object, the error showed up because
of which no element was added to the paper. As soon as the ports are not
added, the error disappears but now I don't have any way to create links.

**Comment by kumilingus** [comment] 2019-09-26 16:40
A code to reproduce this would be great. I've tested several demos and can't reproduce (import from JSON works as expected).

**Comment by snehal96** [comment] 2019-09-27 05:37
well, I tried reproducing the error. The following link shows the error specified when using jointjs v3.0.3
[https://codepen.io/sunny_96/pen/qBWwYVE](url)

**Comment by kumilingus** [comment] 2019-09-27 11:41
Ok, thanks. You should not store custom data under the `attrs` object. The `attrs` object holds presentation attributes that are added to the DOM. It has a given structure `{ [selector]: { [attribute]: value; }}`. A DOM node is found by the `selector` and all `attributes` are set on the node.

In your case, there is`{ attrs: { title: 'Title', check: 'me' })`, which is not valid `attrs` object.

We'll make this part of the code more robust, so it won't fail with this undescriptive error.

If you want to store a cutom data on the model use `set()` or `prop()` instead.

```
model.set('title', 'My Title');
model.prop('data/check', 'me');
```

**Comment by snehal96** [comment] 2019-09-27 11:52
Ohh, thanks a lot
This really was the issue.
It's no where mentioned and this was supported in previous versions so I had no idea what went wrong in the new version.
I'll proceed by correcting those and see if this works out for me finally.

**Comment by snehal96** [comment] 2019-09-30 03:54
Hey, I tried after correcting the mistake. But still the graph import is not coming out correct for me. I implemented it on the same pen. When importing, the port seems to get lost and the links are getting attached to the element's center.
Thanks in advance.

Pen link:
https://codepen.io/sunny_96/pen/qBWwYVE

**Comment by kumilingus** [comment] 2019-09-30 12:20
Ok, I've noticed you were using `joint.shapes.devs.Model`.  Just replace it with `joint.shapes.standard.Rectangle` and it works.

The `devs` shapes has overridden logic for ports (for backwards compatibility) they use `inPorts` and `outPorts` attributes to define the ports (not `ports` attribute). There is no point using `devs` shapes now as ports could be added to an arbitrary shape.

**Comment by snehal96** [comment] 2019-10-01 04:16
well, I tried using `joint.shapes.standard.Rectangle`. But when I use that, ports loose their functionality to create new links. They are like static circles which was not the case in `joint.shapes.devs.Model`.
It would be very helpful if you could provide an example that allows me to create dynamic links between two rectangle that when exported and imported back gives the exact graph.
A small example will also be very helpful.

**Comment by kumilingus** [comment] 2019-10-01 14:11
A port subelement needs to have `magnet` property set to `true` (default logic based on `validateMagnet` paper option).

https://codepen.io/kumilingus/pen/YzKogpa

**Comment by snehal96** [comment] 2019-10-03 04:08
Thanks a lot! That worked out well!
I thought, ports had a default value of magnet as true, but seems like not the case.
Thank you for the help :)

**Closed** 2019-10-03 05:03 UTC
