### ISSUE TITLE
joint.shapes.devs.min.js - "Cannot read property 'define' of undefined"

### ISSUE THREAD

**Issue by Taulant1992** [clientIO/joint#1198] opened 2019-10-10 15:31 UTC
joint.shapes.devs.min.js:10 Uncaught TypeError: Cannot read property 'define' of undefined
    at joint.shapes.devs (joint.shapes.devs.min.js:10)
    at joint.shapes.devs.min.js:182

`var o = e.Generic.define("devs.Model", {...`

e.Generic is undefined.
I suggest to add e.basic.Generic

**Comment by kumilingus** [comment] 2019-10-10 15:35
Duplicate of https://github.com/clientIO/joint/issues/1170.

**Closed by kumilingus** 2019-10-10 15:35 UTC
