### ISSUE TITLE
PhantomJS 2.1.1 > util.breakText hyphen FAILED

### ISSUE THREAD

**Issue by VerscheldeAlynne** [clientIO/joint#1577] opened 2021-11-16 13:57 UTC
It's an assertion that fails, rule 209 from test/jointjs/core/util.js

I found this when running **grunt test**
as in the readme stated i reported this as a bug

![Capture](https://user-images.githubusercontent.com/43439546/141998196-ae9bacb9-3ebb-46a1-9bd6-2f541da9e1d2.PNG)

**Comment by DCMiracle** [comment] 2021-12-02 12:40
me too,help me

**Comment by VerscheldeAlynne** [comment] 2021-12-02 14:34
i think for future-proofing sake, the second and third options would be best. For now though i will employ the first one.

**Comment by DCMiracle** [comment] 2021-12-06 06:43
Have you solved this problem？I installed Courier New font, but it still doesn’t work

**Comment by MartinKanera** [comment] 2022-05-27 10:01
This issue is caused by how PhantomJS renders text and it will be resolved in the future by migrating to puppeteer.

**Comment by kumilingus** [comment] 2022-10-09 15:15
Fixed by https://github.com/clientIO/joint/pull/1795.

**Closed by kumilingus** 2022-10-09 15:15 UTC
Labels: technical debt
