### ISSUE TITLE
How to create an instance of paper with the latest typescript bindings

### ISSUE THREAD

**Issue by srivathsah** [clientIO/joint#887] opened 2018-05-22 19:01 UTC
Hi, I am trying to use joint in a typescript project. I have installed  2.1.2 that happens to be the latest on npm.

I am trying to use the code from [here](https://github.com/CoconutTheSlayer/jointangular2/blob/master/src/app/app.component.ts) as an example.

it shows to create Paper object using
`new joint.dia.Paper({ el: $('body'), width: 500, height: 500, model: this.graph })`

However the issue is in the latest type bindings, I cannot see a model property in Paper.Options
Could you please guide with the right way of creating a paper object ? Thanks

**Comment by kumilingus** [comment] 2018-05-23 08:01
Duplicate of https://github.com/clientIO/joint/issues/797.

You are missing Backbone typings.
```
npm install @types/backbone --save-dev
```

**Closed by kumilingus** 2018-05-23 08:01 UTC
