### ISSUE TITLE
Issue with links generating black block

### ISSUE THREAD

**Issue by sunrock** [clientIO/joint#627] opened 2017-08-29 00:51 UTC
Hi,

![screen shot 2017-08-29 at 10 50 22 am](https://user-images.githubusercontent.com/12167049/29799574-e559d8ca-8ca7-11e7-9623-5807faac43b1.png)
I just simply used the demo code on https://resources.jointjs.com/tutorials/joint/tutorials/hyperlinks.html

but when I add vertices, the link generates an ugly black block. Any suggestions about how to solve that will be appreciated. Many Thanks.

Ruoke

**Comment by kumilingus** [comment] 2017-08-29 06:46
Duplicate of #568.

**Closed by kumilingus** 2017-08-29 06:46 UTC
