### ISSUE TITLE
Regression: Paper.validateConnection

### ISSUE THREAD

**Issue by janhmueller** [clientIO/joint#886] opened 2018-05-22 14:38 UTC
I use dia.Paper.prototype.options.validateConnection(cellViewS, magnetS, cellViewT, magnetT, end, linkView) to validate links. However, after upgrading to 2.1.2, the magnetS - parameter is not longer set.
I think I can trace this back to a change in method 'getLinkEnd()' in file 'joint.dia.cell.js'. It is called from dragMagnetStart(). The change was introduced with commit "dia.LinkView: anchors and connection points" (3652d07054571af0d49b4986b6b2ee91566e44e7) on March, 27th.
The field 'end.selector' is not properly set.
Lines 941pp:
```
        if (port != null) ~~{~~
            end.port = port;
            if (!model.hasPort(port) && !selector) {
                // port created via the `port` attribute (not API)
                end.selector = this.getSelector(magnet);
            }
       ~~}~~ else if (selector == null && this.el !== magnet) {
            end.selector = this.getSelector(magnet);
        }
```
Moving the ' } else if (selector == null && this.el !== magnet) {' clause one level down by removing the brackets seems to fix it.

**Comment by kumilingus** [comment] 2018-05-22 20:03
Hi, thank you for reporting this.

There is a new property `end.magnet`referencing the magnet by its unique selector defined in the JSON markup.
```
// markup: [{ tagName: 'circle', selector: 'my-port' }]
magnet === 'my-port'
```
The `end.selector` property referencing the magnet by a CSS selector. This does not work correctly when the markup of the element changes dynamically + it's slower and ugly.
```
selector === 'g:nth-child(1) > text:nth-child(2)'
```

In the latest version, we don't include `selector` unless is necessary (missing unique selector).

It seems the issue is caused inside `_createValidateConnectionArgs()`, where we don't take the `magnet` property into account. 

Fix: #888

**Comment by janhmueller** [comment] 2018-05-24 11:27
Thanks for creating the patch. I reworked the definition of the ports and added selector fields to the markup and I applied the patch. It works now.

**Comment by kumilingus** [comment] 2018-05-25 12:31
Fixed in https://github.com/clientIO/joint/commit/8a6d13350e1fbb62fa5657a6f6c72504d2e8fa3e.

**Closed** 2018-06-01 11:28 UTC
