### ISSUE TITLE
Grandchild of DEV shape goes into infinite loop in initialization

### ISSUE THREAD

**Issue by mickeyvip** [clientIO/joint#185] opened 2015-09-17 20:36 UTC
If I have a grandchild of a DEV shape (didn't test other classes):
```javascript
joint.shapes.devs.MyModel1 = joint.shapes.devs.Model.extend({
	defaults: joint.util.deepSupplement({
		type: 'devs.MyModel1',
		attrs: {
			'.body': {stroke: 'blue', fill: 'lightblue'}
		}
	}, joint.shapes.devs.Model.prototype.defaults)
});

joint.shapes.devs.MyModel2 = joint.shapes.devs.MyModel1.extend({
	defaults: joint.util.deepSupplement({
		type: 'devs.MyModel2',
		attrs: {
			'.body': {stroke: 'red', fill: 'yellow'}
		}
	}, joint.shapes.devs.MyModel1.prototype.defaults)
});
```

then this line will go into infinite loop:
```javascript
var m1 = new joint.shapes.devs.MyModel2({
	position: { x: 50, y: 50 },
	size: { width: 90, height: 90 },
	inPorts: ['in1','in2'],
	outPorts: ['out'],
	attrs: {
		'.label': { text: 'Model', 'ref-x': 0.4, 'ref-y': 0.2 }
	}
});
```

**Comment by kumilingus** [comment] 2016-10-05 11:01
Fixed in `v1.0.1` - caused by `joint.shapes.basic.PortsModelInterface` (deprecated now).

**Closed by kumilingus** 2016-10-05 11:01 UTC
Labels: bug
