### ISSUE TITLE
[BMPN] Pool label rotation bug in Internet Explorer 11 (Windows 10)

### ISSUE THREAD

**Issue by nico-onmap** [clientIO/joint#648] opened 2017-09-11 14:05 UTC
With the latest version of Rappid (2.1), there seem to be a bug with Pool labels on Internet Explorer 11.

Here is how the label appear on this browser;

![bugie11](https://user-images.githubusercontent.com/26772786/30278547-e67fea6a-970a-11e7-803b-deda8236c1a4.png)

To reproduce it, simply open the [bpmn demo](https://resources.jointjs.com/demos/bpmn) on Internet Explorer 11 / Windows 10 and drop a pool onto the paper.

**Comment by kumilingus** [comment] 2017-09-11 14:42
I believe this issue was fixed by https://github.com/clientIO/joint/pull/586. It will be part of the next release at the end of September.

**Comment by warpdesign** [comment] 2017-09-12 09:11
I applied the commit patch to the 2.1 release I have and the problem is till there.

**Comment by kumilingus** [comment] 2017-09-12 11:00
Please make sure the browser cache is cleared. I've tested the latest version and the issue is not there anymore (and there was not that many changes made in the way attributes work). If the cache is not the issue I'll keep digging what exactly made the issue disappear. Thanks.

**Comment by warpdesign** [comment] 2017-09-12 12:05
I did clear the cache so I don't think it is the issue.

**Comment by kumilingus** [comment] 2017-09-13 12:33
I was wrong. The issue was actually fixed by https://github.com/clientIO/joint/commit/a3c939264eb08947947d2c09dfcc2ba9ffcae7cd.

**Closed** 2017-11-07 08:05 UTC
