### ISSUE TITLE
Joint Js 0.9.5 HTML Elements not rendering

### ISSUE THREAD

**Issue by JonBirch** [clientIO/joint#201] opened 2015-11-15 14:16 UTC
Hey, I debated whether or not to post this as a bug for the past few days however after doing a bit more testing I believe it is. Using the the Html elements example from your web page I drafted a little example of my own. However when I run the example the svg canvas loads but the html elements that are suppose to overlay do not get added to the DOM. This is using the latest version of the library 0.9.5.
If I run the same exact example instead including the 0.9.3 version it renders perfectly.
An example of the issue can be found here
http://stackoverflow.com/questions/33713375/can-not-get-html-elements-working-with-joint-js

I apologize if this example is using deprecated functionality and as a result no working. I did however check the change logs and nothing seems to stand out that would cause this functionally to break.

**Comment by kumilingus** [comment] 2015-12-11 10:39
Duplicate of https://github.com/clientIO/joint/issues/198

**Closed by kumilingus** 2015-12-11 10:39 UTC
