### ISSUE TITLE
Joint 2.0.1 - Setting size of elements in a hidden graph is buggy

### ISSUE THREAD

**Issue by coroiu** [clientIO/joint#881] opened 2018-05-15 10:23 UTC
Hiding the graph by setting `display: none` to it's parent container and then attempting to change the sizes of the elements results in extreme sizes. Quick look at the dom reveals huge scaling numbers (in the hundreds) instead of 0.6 that they normaly are set to. Not sure if this is what results in the buggy behavior.

**Comment by kumilingus** [comment] 2018-05-17 10:30
Duplicate of #262.

The issue does not exist for `joint.shapes.standard` shapes for several reasons.

1. Shapes are defined without `scalable` group inside their markup.
2. Shapes do not use `yAlignment`, `xAlignment` and `resetOffset` attributes. (these internally perform measuring on DOM elements).
3. Shapes do not use `ref` attribute referencing another DOM element (same reason as no. 2).

**Closed by kumilingus** 2018-05-17 10:30 UTC
