### ISSUE TITLE
Joint Rappid Chart

### ISSUE THREAD

**Issue by mkolasinski** [clientIO/joint#743] opened 2017-10-25 10:45 UTC
I'm a beginner in using joint. I want to exercise tasks from tutorial and I'd like to do a simple chart.
I have a problem, it's my code: 

import { Component, OnInit } from '@angular/core';
import { dia, shapes } from 'jointjs';
import * as $ from 'jquery';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {

  ngOnInit() {

    let graph = new dia.Graph;
    let paper = new dia.Paper({
        el: $('#paper'),
        width: 600,
        height: 600,
        model: graph
    });

    let chart = new shapes.chart.Knob({
        position: { x: 350, y: 350 },
        size: { width: 100, height: 100 },
        min: 0,
        max: 100,
        value: 80,
        fill: 'darkblue'
    });
    graph.addCell(chart);
  }
}

In terminal the error shows me that: Property 'chart' does not exist on type 'typeof shapes'. Could someone help me???

**Comment by kumilingus** [comment] 2017-10-31 20:11
Hi Michal, the problem is that Rappid currently missing TS definitions for Chart shapes. Before we add the definitions I suggest to do the following:

```javascript
let chart = shapes['chart']['Knob']({ /* ... */ })
```

**Comment by mkolasinski** [comment] 2017-11-02 11:11
Ok, your suggestion is ok because I don't see any errors but still I can't show my chart...What should I import?&nbsp;import { shapes } from 'jointjs' ?? or what?-- mgr inż. Michał KolasińskiOd: "Roman Bruckner" &lt;notifications@github.com&gt;Do: "clientIO/joint" &lt;joint@noreply.github.com&gt;; Wysłane: 21:11 Wtorek 2017-10-31Temat: Re: [clientIO/joint] Joint Rappid Chart (#743)Hi Michal, the problem is that Rappid currently missing TS definitions for Chart shapes. Before we add the definitions I suggest to do the following:
let chart = shapes['chart']['Knob']({ /* ... */ })

**Comment by mkolasinski** [comment] 2017-11-02 13:48
Hi thanks for your suggestion. 
After using that, I don't show errors ( so it's okay ) but I don't create a simple chart. 
Maybe I have a problem with import {dia, shapes} from 'jointjs' ?

Regards,

**Comment by kumilingus** [comment] 2018-09-26 22:01
Fixed in Rappid `v2.3.3`.

**Closed by kumilingus** 2018-09-26 22:01 UTC
Labels: typescript
