### ISSUE TITLE
joint.dia.Paper#pointerup should set _mousemoved to false

### ISSUE THREAD

**Issue by BoykoAlex** [clientIO/joint#197] opened 2015-10-21 05:18 UTC
Currently if I create a connection between 2 ports with Joint JS core pointermove function would set _mousemoved to true but there is nothing to set it to false. Therefore next pointerclick event just deosn't happen. One would need to click twice to get pointerclick event after creating a link between 2 ports.

**Comment by kumilingus** [comment] 2015-10-21 08:03
Hi, we should really reset `_mousemoved` on pointer down. Thank you for reporting this.

**Comment by chill117** [comment] 2015-11-04 09:14
I am not able to reproduce this problem. Could you provide me with exact steps to reproduce the issue?

**Comment by chill117** [comment] 2015-11-18 11:39
Just checking in. Are you still experiencing the issue?

**Comment by charnog** [comment] 2015-11-19 12:11
@kumilingus, @chill117, can't reproduce it as described by @BoykoAlex, but if I start to drag something and drag it out the window or SVG container (for example) _mousemove won't be cleared! So the next mouseclick won't be fired for one time.

**Comment by chill117** [comment] 2015-11-20 14:58
I tried multiple different ways to reproduce this, and I still cannot. Can you provide a JSFiddle or some sample code (with JointJS version number)?

**Comment by kumilingus** [comment] 2015-12-08 16:11
Fixed in v0.9.6 (`_mousemoved` counter is alwyas reset on mousedown event).

**Closed by kumilingus** 2015-12-08 16:11 UTC
