### ISSUE TITLE
[Bug]: fromJson() method is invoking illegal access error

### ISSUE THREAD

**Issue by ashish141199** [clientIO/joint#1987] opened 2023-01-15 07:34 UTC
### What happened?

I'm using a simple element connection graph. But when suddenly, (unable to determine the pattern), I get the below mentioned error. This happens when at the time of loading of the graph using `fromJson()`.

Please let me know if there's any solution to this. 

Thanks in advance!

Console Error:
```
Uncaught (in promise) Error: Illegal access. Moveto segments should not need a start property.
    at Proxy.get (path.mjs:2119:15)
    at Reflect.get (<anonymous>)
    at Object.get2 [as get] (reactivity.esm-bundler.js:475:29)
    at traverse (runtime-core.esm-bundler.js:1920:22)
    at traverse (runtime-core.esm-bundler.js:1910:13)
    at traverse (runtime-core.esm-bundler.js:1920:13)
    at traverse (runtime-core.esm-bundler.js:1920:13)
    at traverse (runtime-core.esm-bundler.js:1920:13)
    at traverse (runtime-core.esm-bundler.js:1920:13)
    at traverse (runtime-core.esm-bundler.js:1920:13)
get @ path.mjs:2119
get2 @ reactivity.esm-bundler.js:475
traverse @ runtime-core.esm-bundler.js:1920
traverse @ runtime-core.esm-bundler.js:1910
traverse @ runtime-core.esm-bundler.js:1920
traverse @ runtime-core.esm-bundler.js:1920
traverse @ runtime-core.esm-bundler.js:1920
traverse @ runtime-core.esm-bundler.js:1920
traverse @ runtime-core.esm-bundler.js:1920
traverse @ runtime-core.esm-bundler.js:1920
traverse @ runtime-core.esm-bundler.js:1910
traverse @ runtime-core.esm-bundler.js:1920
traverse @ runtime-core.esm-bundler.js:1920
traverse @ runtime-core.esm-bundler.js:1910
traverse @ runtime-core.esm-bundler.js:1920
traverse @ runtime-core.esm-bundler.js:1920
traverse @ runtime-core.esm-bundler.js:1920
traverse @ runtime-core.esm-bundler.js:1920
getter @ runtime-core.esm-bundler.js:1742
run @ reactivity.esm-bundler.js:187
job @ runtime-core.esm-bundler.js:1783
triggerEffect @ reactivity.esm-bundler.js:397
triggerEffects @ reactivity.esm-bundler.js:387
trigger @ reactivity.esm-bundler.js:370
set2 @ reactivity.esm-bundler.js:523
onApi @ backbone.js:165
eventsApi @ backbone.js:106
Events.on @ backbone.js:118
setListeners @ LogicBuilderService.ts:162
initPaper @ LogicBuilderService.ts:154
(anonymous) @ runtime-core.esm-bundler.js:2739
callWithErrorHandling @ runtime-core.esm-bundler.js:157
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:166
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:2713
flushPostFlushCbs @ runtime-core.esm-bundler.js:343
flushJobs @ runtime-core.esm-bundler.js:397
Promise.catch (async)
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:168
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:2713
flushPostFlushCbs @ runtime-core.esm-bundler.js:343
flushJobs @ runtime-core.esm-bundler.js:397
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:282
queueJob @ runtime-core.esm-bundler.js:276
(anonymous) @ runtime-core.esm-bundler.js:5743
triggerEffect @ reactivity.esm-bundler.js:397
triggerEffects @ reactivity.esm-bundler.js:387
triggerRefValue @ reactivity.esm-bundler.js:1003
(anonymous) @ reactivity.esm-bundler.js:1137
triggerEffect @ reactivity.esm-bundler.js:397
triggerEffects @ reactivity.esm-bundler.js:382
triggerRefValue @ reactivity.esm-bundler.js:1003
(anonymous) @ reactivity.esm-bundler.js:1137
triggerEffect @ reactivity.esm-bundler.js:397
triggerEffects @ reactivity.esm-bundler.js:382
trigger @ reactivity.esm-bundler.js:355
set2 @ reactivity.esm-bundler.js:526
update @ quasar.esm.js:22825
updateLayout @ quasar.esm.js:20356
setup @ quasar.esm.js:20409
callWithErrorHandling @ runtime-core.esm-bundler.js:157
setupStatefulComponent @ runtime-core.esm-bundler.js:7246
setupComponent @ runtime-core.esm-bundler.js:7201
mountComponent @ runtime-core.esm-bundler.js:5524
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
mountChildren @ runtime-core.esm-bundler.js:5285
processFragment @ runtime-core.esm-bundler.js:5458
patch @ runtime-core.esm-bundler.js:5094
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
mountChildren @ runtime-core.esm-bundler.js:5285
mountElement @ runtime-core.esm-bundler.js:5195
processElement @ runtime-core.esm-bundler.js:5178
patch @ runtime-core.esm-bundler.js:5098
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
(anonymous) @ runtime-core.esm-bundler.js:1487
Promise.then (async)
registerDep @ runtime-core.esm-bundler.js:1466
mountComponent @ runtime-core.esm-bundler.js:5532
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
mountSuspense @ runtime-core.esm-bundler.js:1209
process @ runtime-core.esm-bundler.js:1185
patch @ runtime-core.esm-bundler.js:5107
mountChildren @ runtime-core.esm-bundler.js:5285
processFragment @ runtime-core.esm-bundler.js:5458
patch @ runtime-core.esm-bundler.js:5094
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
mountChildren @ runtime-core.esm-bundler.js:5285
mountElement @ runtime-core.esm-bundler.js:5195
processElement @ runtime-core.esm-bundler.js:5178
patch @ runtime-core.esm-bundler.js:5098
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
mountChildren @ runtime-core.esm-bundler.js:5285
mountElement @ runtime-core.esm-bundler.js:5195
processElement @ runtime-core.esm-bundler.js:5178
patch @ runtime-core.esm-bundler.js:5098
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
(anonymous) @ runtime-core.esm-bundler.js:1487
Promise.then (async)
registerDep @ runtime-core.esm-bundler.js:1466
mountComponent @ runtime-core.esm-bundler.js:5532
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
mountChildren @ runtime-core.esm-bundler.js:5285
processFragment @ runtime-core.esm-bundler.js:5458
patch @ runtime-core.esm-bundler.js:5094
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
mountChildren @ runtime-core.esm-bundler.js:5285
processFragment @ runtime-core.esm-bundler.js:5458
patch @ runtime-core.esm-bundler.js:5094
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
mountSuspense @ runtime-core.esm-bundler.js:1209
process @ runtime-core.esm-bundler.js:1185
patch @ runtime-core.esm-bundler.js:5107
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
render2 @ runtime-core.esm-bundler.js:6260
mount @ runtime-core.esm-bundler.js:4456
app.mount @ runtime-dom.esm-bundler.js:1607
initApp @ entry.mjs:47
await in initApp (async)
(anonymous) @ entry.mjs:55

```

### Version

3.6.5

### What browsers are you seeing the problem on?

Chrome

### What operating system are you seeing the problem on?

Windows

**Comment by kumilingus** [comment] 2023-01-15 07:38
What is the JSON?

**Comment by ashish141199** [comment] 2023-01-15 08:28
```
{
  "cells": [
    {
      "type": "standard.Rectangle",
      "position": {
        "x": 420,
        "y": 630
      },
      "size": {
        "width": 150,
        "height": 60
      },
      "angle": 0,
      "ports": {
        "groups": {
          "in": {
            "position": {
              "name": "top"
            },
            "attrs": {
              "portBody": {
                "magnet": "passive",
                "r": 10,
                "fill": "white",
                "stroke": "green",
                "style": {
                  "cursor": "inherit",
                  "user-select": "none"
                }
              }
            },
            "label": {
              "position": {
                "name": "top"
              },
              "markup": [
                {
                  "tagName": "text",
                  "selector": "label",
                  "className": "port-label-text"
                }
              ]
            },
            "markup": [
              {
                "tagName": "circle",
                "selector": "portBody"
              }
            ]
          },
          "out": {
            "position": {
              "name": "bottom"
            },
            "attrs": {
              "portBody": {
                "magnet": true,
                "r": 10,
                "fill": "red",
                "stroke": "white",
                "style": {
                  "cursor": "crosshair",
                  "user-select": "none"
                }
              }
            },
            "label": {
              "position": {
                "name": "bottom"
              },
              "markup": [
                {
                  "tagName": "text",
                  "selector": "label",
                  "className": "port-label-text"
                }
              ]
            },
            "markup": [
              {
                "tagName": "circle",
                "selector": "portBody"
              }
            ]
          }
        },
        "items": [
          {
            "group": "in",
            "attrs": {
              "data": {
                "blockId": "9e3ca638-28b7-472e-92c1-8ef500045f24"
              }
            },
            "id": "fae29921-04c8-49ab-83bc-ead54cb71455"
          },
          {
            "group": "out",
            "attrs": {
              "data": {
                "blockId": "9e3ca638-28b7-472e-92c1-8ef500045f24"
              }
            },
            "id": "52a80274-481e-4cbb-a15d-894a24927aea"
          }
        ]
      },
      "id": "3be67827-a6f3-413b-9d7f-df69d1a48416",
      "data": {
        "blockId": "9e3ca638-28b7-472e-92c1-8ef500045f24"
      },
      "z": 1,
      "attrs": {
        "body": {
          "strokeWidth": 1,
          "stroke": "blue",
          "fill": "white",
          "rx": 4,
          "ry": 4,
          "filter": {
            "name": "dropShadow",
            "args": {
              "dx": 0,
              "dy": 0.5,
              "blur": 1
            }
          },
          "style": {
            "cursor": "move"
          }
        },
        "label": {
          "fill": "blue",
          "text": "Get Model Instance",
          "style": {
            "cursor": "pointer",
            "fontSize": "12px",
            "fontWeight": "bold"
          }
        }
      }
    },
    {
      "type": "standard.Rectangle",
      "position": {
        "x": 405,
        "y": 510
      },
      "size": {
        "width": 150,
        "height": 60
      },
      "angle": 0,
      "ports": {
        "groups": {
          "in": {
            "position": {
              "name": "top"
            },
            "attrs": {
              "portBody": {
                "magnet": "passive",
                "r": 10,
                "fill": "white",
                "stroke": "green",
                "style": {
                  "cursor": "inherit",
                  "user-select": "none"
                }
              }
            },
            "label": {
              "position": {
                "name": "top"
              },
              "markup": [
                {
                  "tagName": "text",
                  "selector": "label",
                  "className": "port-label-text"
                }
              ]
            },
            "markup": [
              {
                "tagName": "circle",
                "selector": "portBody"
              }
            ]
          },
          "out": {
            "position": {
              "name": "bottom"
            },
            "attrs": {
              "portBody": {
                "magnet": true,
                "r": 10,
                "fill": "red",
                "stroke": "white",
                "style": {
                  "cursor": "crosshair",
                  "user-select": "none"
                }
              }
            },
            "label": {
              "position": {
                "name": "bottom"
              },
              "markup": [
                {
                  "tagName": "text",
                  "selector": "label",
                  "className": "port-label-text"
                }
              ]
            },
            "markup": [
              {
                "tagName": "circle",
                "selector": "portBody"
              }
            ]
          }
        },
        "items": [
          {
            "group": "in",
            "attrs": {
              "data": {
                "blockId": "2816d252-63b8-4ec9-98a9-8f7df3c77fd0"
              }
            },
            "id": "6e2f9e14-e112-4f9f-a323-9575319f13f9"
          },
          {
            "group": "out",
            "attrs": {
              "data": {
                "blockId": "2816d252-63b8-4ec9-98a9-8f7df3c77fd0"
              },
              "portBody": {
                "fill": "green"
              }
            },
            "id": "0db7835a-f1ff-40da-9467-493e65bcf4c6"
          }
        ]
      },
      "id": "a5f0ab82-d8d7-4995-b8db-5ad940466b05",
      "data": {
        "blockId": "2816d252-63b8-4ec9-98a9-8f7df3c77fd0"
      },
      "z": 2,
      "attrs": {
        "body": {
          "strokeWidth": 1,
          "stroke": "blue",
          "fill": "white",
          "rx": 4,
          "ry": 4,
          "filter": {
            "name": "dropShadow",
            "args": {
              "dx": 0,
              "dy": 0.5,
              "blur": 1
            }
          },
          "style": {
            "cursor": "move"
          }
        },
        "label": {
          "fill": "blue",
          "text": "Delete Model\nInstance",
          "style": {
            "cursor": "pointer",
            "fontSize": "12px",
            "fontWeight": "bold"
          }
        }
      }
    },
    {
      "type": "standard.Rectangle",
      "position": {
        "x": 405,
        "y": 420
      },
      "size": {
        "width": 150,
        "height": 60
      },
      "angle": 0,
      "ports": {
        "groups": {
          "in": {
            "position": {
              "name": "top"
            },
            "attrs": {
              "portBody": {
                "magnet": "passive",
                "r": 10,
                "fill": "white",
                "stroke": "green",
                "style": {
                  "cursor": "inherit",
                  "user-select": "none"
                }
              }
            },
            "label": {
              "position": {
                "name": "top"
              },
              "markup": [
                {
                  "tagName": "text",
                  "selector": "label",
                  "className": "port-label-text"
                }
              ]
            },
            "markup": [
              {
                "tagName": "circle",
                "selector": "portBody"
              }
            ]
          },
          "out": {
            "position": {
              "name": "bottom"
            },
            "attrs": {
              "portBody": {
                "magnet": true,
                "r": 10,
                "fill": "red",
                "stroke": "white",
                "style": {
                  "cursor": "crosshair",
                  "user-select": "none"
                }
              }
            },
            "label": {
              "position": {
                "name": "bottom"
              },
              "markup": [
                {
                  "tagName": "text",
                  "selector": "label",
                  "className": "port-label-text"
                }
              ]
            },
            "markup": [
              {
                "tagName": "circle",
                "selector": "portBody"
              }
            ]
          }
        },
        "items": [
          {
            "group": "in",
            "attrs": {
              "data": {
                "blockId": "7f4f5d5b-5971-4b51-9bfa-87bc6ff94163"
              }
            },
            "id": "862151df-c703-44be-a5e2-cd6bd76101a1"
          },
          {
            "group": "out",
            "attrs": {
              "data": {
                "blockId": "7f4f5d5b-5971-4b51-9bfa-87bc6ff94163"
              },
              "portBody": {
                "fill": "green"
              }
            },
            "id": "c1340ead-ea6a-44b5-b975-65620da3b537"
          }
        ]
      },
      "id": "75d5023f-a187-478a-9015-c988b5cbc02a",
      "data": {
        "blockId": "7f4f5d5b-5971-4b51-9bfa-87bc6ff94163"
      },
      "z": 3,
      "attrs": {
        "body": {
          "strokeWidth": 1,
          "stroke": "purple",
          "fill": "white",
          "rx": 4,
          "ry": 4,
          "filter": {
            "name": "dropShadow",
            "args": {
              "dx": 0,
              "dy": 0.5,
              "blur": 1
            }
          },
          "style": {
            "cursor": "move"
          }
        },
        "label": {
          "fill": "purple",
          "text": "Console Log",
          "style": {
            "cursor": "pointer",
            "fontSize": "12px",
            "fontWeight": "bold"
          }
        }
      }
    },
    {
      "type": "standard.Rectangle",
      "position": {
        "x": 405,
        "y": 315
      },
      "size": {
        "width": 150,
        "height": 60
      },
      "angle": 0,
      "ports": {
        "groups": {
          "in": {
            "position": {
              "name": "top"
            },
            "attrs": {
              "portBody": {
                "magnet": "passive",
                "r": 10,
                "fill": "white",
                "stroke": "green",
                "style": {
                  "cursor": "inherit",
                  "user-select": "none"
                }
              }
            },
            "label": {
              "position": {
                "name": "top"
              },
              "markup": [
                {
                  "tagName": "text",
                  "selector": "label",
                  "className": "port-label-text"
                }
              ]
            },
            "markup": [
              {
                "tagName": "circle",
                "selector": "portBody"
              }
            ]
          },
          "out": {
            "position": {
              "name": "bottom"
            },
            "attrs": {
              "portBody": {
                "magnet": true,
                "r": 10,
                "fill": "red",
                "stroke": "white",
                "style": {
                  "cursor": "crosshair",
                  "user-select": "none"
                }
              }
            },
            "label": {
              "position": {
                "name": "bottom"
              },
              "markup": [
                {
                  "tagName": "text",
                  "selector": "label",
                  "className": "port-label-text"
                }
              ]
            },
            "markup": [
              {
                "tagName": "circle",
                "selector": "portBody"
              }
            ]
          }
        },
        "items": [
          {
            "group": "in",
            "attrs": {
              "data": {
                "blockId": "d070c459-6f8d-42ed-8fb9-04787f1654c5"
              }
            },
            "id": "38141bcb-92c6-4e94-b613-ab04d121f044"
          },
          {
            "group": "out",
            "attrs": {
              "data": {
                "blockId": "d070c459-6f8d-42ed-8fb9-04787f1654c5"
              },
              "portBody": {
                "fill": "green"
              }
            },
            "id": "591bdf5b-ffbf-457c-afdc-f5fb38a03808"
          }
        ]
      },
      "id": "150f8194-df2b-4b2f-9cbe-bdc6be51830d",
      "data": {
        "blockId": "d070c459-6f8d-42ed-8fb9-04787f1654c5"
      },
      "z": 4,
      "attrs": {
        "body": {
          "strokeWidth": 1,
          "stroke": "green",
          "fill": "white",
          "rx": 4,
          "ry": 4,
          "filter": {
            "name": "dropShadow",
            "args": {
              "dx": 0,
              "dy": 0.5,
              "blur": 1
            }
          },
          "style": {
            "cursor": "move"
          }
        },
        "label": {
          "fill": "green",
          "text": "Show Alert",
          "style": {
            "cursor": "pointer",
            "fontSize": "12px",
            "fontWeight": "bold"
          }
        }
      }
    },
    {
      "type": "standard.Rectangle",
      "position": {
        "x": 435,
        "y": 135
      },
      "size": {
        "width": 150,
        "height": 60
      },
      "angle": 0,
      "ports": {
        "groups": {
          "in": {
            "position": {
              "name": "top"
            },
            "attrs": {
              "portBody": {
                "magnet": "passive",
                "r": 10,
                "fill": "white",
                "stroke": "green",
                "style": {
                  "cursor": "inherit",
                  "user-select": "none"
                }
              }
            },
            "label": {
              "position": {
                "name": "top"
              },
              "markup": [
                {
                  "tagName": "text",
                  "selector": "label",
                  "className": "port-label-text"
                }
              ]
            },
            "markup": [
              {
                "tagName": "circle",
                "selector": "portBody"
              }
            ]
          },
          "out": {
            "position": {
              "name": "bottom"
            },
            "attrs": {
              "portBody": {
                "magnet": true,
                "r": 10,
                "fill": "red",
                "stroke": "white",
                "style": {
                  "cursor": "crosshair",
                  "user-select": "none"
                }
              }
            },
            "label": {
              "position": {
                "name": "bottom"
              },
              "markup": [
                {
                  "tagName": "text",
                  "selector": "label",
                  "className": "port-label-text"
                }
              ]
            },
            "markup": [
              {
                "tagName": "circle",
                "selector": "portBody"
              }
            ]
          }
        },
        "items": [
          {
            "group": "in",
            "attrs": {
              "data": {
                "blockId": "bc3fba6a-4dde-4737-865b-9e260d367b1b"
              }
            },
            "id": "f3171950-0068-4ab1-bdeb-55598e4acb64"
          },
          {
            "group": "out",
            "attrs": {
              "data": {
                "blockId": "bc3fba6a-4dde-4737-865b-9e260d367b1b"
              },
              "portBody": {
                "fill": "green"
              }
            },
            "id": "e92c0723-2973-4279-92e1-c239b7398621"
          }
        ]
      },
      "id": "ff1d901a-0b4c-4655-986e-0e13e62af647",
      "data": {
        "blockId": "bc3fba6a-4dde-4737-865b-9e260d367b1b"
      },
      "z": 5,
      "attrs": {
        "body": {
          "strokeWidth": 1,
          "stroke": "green",
          "fill": "white",
          "rx": 4,
          "ry": 4,
          "filter": {
            "name": "dropShadow",
            "args": {
              "dx": 0,
              "dy": 0.5,
              "blur": 1
            }
          },
          "style": {
            "cursor": "move"
          }
        },
        "label": {
          "fill": "green",
          "text": "Navigate",
          "style": {
            "cursor": "pointer",
            "fontSize": "12px",
            "fontWeight": "bold"
          }
        }
      }
    },
    {
      "type": "standard.Link",
      "source": {
        "id": "ff1d901a-0b4c-4655-986e-0e13e62af647",
        "magnet": "portBody",
        "port": "e92c0723-2973-4279-92e1-c239b7398621"
      },
      "target": {
        "id": "150f8194-df2b-4b2f-9cbe-bdc6be51830d",
        "magnet": "portBody",
        "port": "38141bcb-92c6-4e94-b613-ab04d121f044"
      },
      "id": "82011393-66f9-489a-82a5-855048bd8188",
      "z": 6,
      "attrs": {
        "line": {
          "stroke": "green"
        }
      }
    },
    {
      "type": "standard.Link",
      "source": {
        "id": "150f8194-df2b-4b2f-9cbe-bdc6be51830d",
        "magnet": "portBody",
        "port": "591bdf5b-ffbf-457c-afdc-f5fb38a03808"
      },
      "target": {
        "id": "75d5023f-a187-478a-9015-c988b5cbc02a",
        "magnet": "portBody",
        "port": "862151df-c703-44be-a5e2-cd6bd76101a1"
      },
      "id": "1c3e9c3b-8a0c-4964-b93f-3583bf2bf513",
      "z": 7,
      "attrs": {
        "line": {
          "stroke": "green"
        }
      }
    },
    {
      "type": "standard.Link",
      "source": {
        "id": "75d5023f-a187-478a-9015-c988b5cbc02a",
        "magnet": "portBody",
        "port": "c1340ead-ea6a-44b5-b975-65620da3b537"
      },
      "target": {
        "id": "a5f0ab82-d8d7-4995-b8db-5ad940466b05",
        "magnet": "portBody",
        "port": "6e2f9e14-e112-4f9f-a323-9575319f13f9"
      },
      "id": "83e14311-943a-4bf7-a929-b9ef3e1f4e1a",
      "z": 8,
      "attrs": {
        "line": {
          "stroke": "green"
        }
      }
    },
    {
      "type": "standard.Link",
      "source": {
        "id": "a5f0ab82-d8d7-4995-b8db-5ad940466b05",
        "magnet": "portBody",
        "port": "0db7835a-f1ff-40da-9467-493e65bcf4c6"
      },
      "target": {
        "id": "3be67827-a6f3-413b-9d7f-df69d1a48416",
        "magnet": "portBody",
        "port": "fae29921-04c8-49ab-83bc-ead54cb71455"
      },
      "id": "cd9e3674-8a10-47b6-b8a5-1c89e2d18d78",
      "z": 9,
      "attrs": {
        "line": {
          "stroke": "green"
        }
      }
    }
  ]
}
```

**Comment by ashish141199** [comment] 2023-01-15 08:29
This is the JSON. Although, upon digging further, I found out that fromJSON isn't the issue. But this error is triggered after setting an event listener on graph object.

`store.graph.on("change:source change:target", (link) => onLinkEstablished(link))`

**Comment by kumilingus** [comment] 2023-01-15 08:42
It does not sound right (`.on()` method does not execute any JointJS code). Perhaps the error is triggered when the `source` or `target`  is changed i.e. `onLinkEstablished` is called.

The exception is triggered by the `geometry` library [here](https://github.com/clientIO/joint/blob/master/src/g/path.mjs#L2119). Someone is trying to call `start` method on `Move` segment.

Try to create a reproducible example, please. There is not much we can do to help you at this point.

**Comment by ashish141199** [comment] 2023-01-15 10:39
Yes. The error is indeed triggered when source or target is changed! I'm unable to create a reproducible example, because it sometimes works and sometimes doesn't. Unable to find exactly what the reason or action could be that is triggering the error

**Comment by kumilingus** [comment] 2023-01-15 14:20
So what does the `onLinkEstablished` function do?

**Comment by ashish141199** [comment] 2023-01-15 15:46
```
// executed when link is established between two elements
    function onLinkEstablished(link: joint.dia.Link) {
        const { findBlockByElement } = useLogicBlockManagerService(); // can call because the two functions aren't interdependent on each other - hence avoiding "maximum call stack exceeded" error
        // get the source and target block
        const source = link.get('source');
        const target = link.get('target');
        if (!source.id || !target.id) return; // end the execution if any one of these are not given
        const sourceElement = link.getSourceElement();
        const targetElement = link.getTargetElement();
        if (!sourceElement || !targetElement) return;
        sourceElement.portProp(source.port, 'attrs/portBody/fill', 'green') // change the color of sourceCell output port
        const sourceBlock = findBlockByElement(sourceElement);
        const targetBlock = findBlockByElement(targetElement);
        if (!sourceBlock || !targetBlock) return;
        _.set(sourceBlock, 'next', targetBlock._id) // add next in sourceBlock
        _.set(targetBlock, 'previous', sourceBlock._id) // add previous in sourceBlock
    }// executed when link is established between two elements
    function onLinkEstablished(link: joint.dia.Link) {
        const { findBlockByElement } = useLogicBlockManagerService(); // can call because the two functions aren't interdependent on each other - hence avoiding "maximum call stack exceeded" error
        // get the source and target block
        const source = link.get('source');
        const target = link.get('target');
        if (!source.id || !target.id) return; // end the execution if any one of these are not given
        const sourceElement = link.getSourceElement();
        const targetElement = link.getTargetElement();
        if (!sourceElement || !targetElement) return;
        sourceElement.portProp(source.port, 'attrs/portBody/fill', 'green') // change the color of sourceCell output port
        const sourceBlock = findBlockByElement(sourceElement);
        const targetBlock = findBlockByElement(targetElement);
        if (!sourceBlock || !targetBlock) return;
        _.set(sourceBlock, 'next', targetBlock._id) // add next in sourceBlock
        _.set(targetBlock, 'previous', sourceBlock._id) // add previous in sourceBlock
    }
```

Just links two blocks with each other.

**Comment by ashish141199** [comment] 2023-01-15 16:52
Problem solved.  The problem was with Pinia store. I was using JointJS with Vue, Nuxt and Pinia (state management). I was storing the graph in a state management Pinia store. Hence the issue. I still don't know what the root cause was. 

I changed it to a normal global variable and everything worked as expected!

Still would like to know any way to use Graph variable across multiple files? (something like a store)

**Comment by kumilingus** [comment] 2023-01-16 04:57
For that please use [discussions](https://github.com/clientIO/joint/discussions). I am closing the issue as *not a bug*.

**Closed by kumilingus** 2023-01-16 04:57 UTC
